steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        build,
        -f,
        infra/docker/agent.Dockerfile,
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/agent:latest',
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/agent:${_TAG}',
        .,
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        build,
        -f,
        infra/docker/web.Dockerfile,
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:latest',
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:${_TAG}',
        .,
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        build,
        -f,
        infra/docker/browser-job.Dockerfile,
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/browser:latest',
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/browser:${_TAG}',
        .,
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        build,
        -f,
        infra/docker/code-runner.Dockerfile,
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/code:latest',
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/code:${_TAG}',
        .,
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        build,
        -f,
        infra/docker/document-processor.Dockerfile,
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/processor:latest',
        -t,
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/processor:${_TAG}',
        .,
      ]
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/agent:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/agent:${_TAG}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:${_TAG}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/browser:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/browser:${_TAG}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/code:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/code:${_TAG}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/processor:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/processor:${_TAG}'
substitutions:
  _REGION: us-west1
  _REPO: assistant
  _TAG: manual
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
