/** Portable record shapes. PostgreSQL compatibility is checked by records.test.ts.
 * These types are owned by persistence: change them intentionally, not on every SQL migration. */
export interface Records {
  maintenanceCursors: {
    name: string;
    cursor: string | null;
    updatedAt: Date;
  };
  situationPacks: {
    id: string;
    data: unknown;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    creationKey: string;
    title: string;
    version: number;
    archived: boolean;
  };
  situationPreviews: {
    id: string;
    data: unknown;
    createdAt: Date;
    packId: string;
    baseVersion: number;
    sourceHash: string;
    status: string;
    expiresAt: Date;
  };
  agents: {
    id: string;
    name: string;
    email: string;
    calendarId: string | null;
    phoneE164: string | null;
    avatarUrl: string | null;
    signature: string;
    timezone: string;
    locale: string;
    workspacePrefix: string;
    browserProfilePath: string | null;
    credentialRefs: unknown;
    createdAt: Date;
    updatedAt: Date;
  };
  mcpConnections: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    endpoint: string;
    bearerTokenEncrypted: string | null;
    enabled: boolean;
    serverName: string | null;
    serverVersion: string | null;
    instructions: string | null;
    tools: unknown;
    lastCheckedAt: Date | null;
    lastError: string | null;
  };
  goals: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    description: string;
    priority: number;
    progress: string;
    nextAction: string;
    targetDate: Date | null;
    mirrorToPrimary: boolean;
    taintedOrigin: boolean;
    autonomy: boolean;
    archivedAt: Date | null;
  };
  conversations: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    archivedAt: Date | null;
    channel: string;
    trust: string;
    modelOverride: string | null;
    isPrimary: boolean;
    metadata: unknown;
    lastReadAt: Date | null;
  };
  channelBindings: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    channel: string;
    conversationId: string;
    externalId: string;
  };
  messages: {
    id: string;
    createdAt: Date;
    conversationId: string;
    taskId: string | null;
    role: string;
    parts: unknown;
    text: string;
    origin: string;
    channelMessageId: string | null;
    embedding: number[] | null;
  };
  generatedCards: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date | null;
    conversationId: string | null;
    messageId: string | null;
    sourceLabel: string;
    sourceFingerprint: string;
    currentRevisionId: string;
    dismissedAt: Date | null;
  };
  generatedCardRevisions: {
    id: string;
    createdAt: Date;
    version: number;
    cardId: string;
    spec: unknown;
  };
  commitments: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    nextAction: string;
    conversationId: string;
    sourceMessageId: string | null;
    sourceTaskId: string | null;
    kind: string;
    details: string;
    dueAt: Date | null;
    snoozedUntil: Date | null;
    resolvedAt: Date | null;
    resolution: string | null;
    confidence: string;
    contentHash: string;
  };
  conversationSegments: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    conversationId: string;
    embedding: number[] | null;
    startMessageId: string;
    endMessageId: string;
    summary: string;
    messageCount: number;
    startedAt: Date;
    endedAt: Date;
  };
  tasks: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string | null;
    status: string;
    progress: string;
    nextAction: string;
    archivedAt: Date | null;
    trust: string;
    conversationId: string | null;
    type: string;
    goalId: string | null;
    autonomyGrant: unknown;
    trigger: unknown;
    externalEventId: string | null;
    plan: unknown;
    state: unknown;
    progressPercent: number | null;
    deadline: Date | null;
    reflectEvery: string | null;
    lastReflectedAt: Date | null;
    runAfter: Date | null;
    lockedUntil: Date | null;
    leaseToken: string | null;
    queueGeneration: number;
    attempt: number;
    reclaimCount: number;
    maxSteps: number;
    budgetUsdLimit: string;
    spentUsd: string;
    parentTaskId: string | null;
    attentionNotifiedAt: Date | null;
  };
  toolCalls: {
    id: string;
    createdAt: Date;
    status: string;
    taskId: string;
    startedAt: Date | null;
    step: number;
    toolName: string;
    args: unknown;
    risk: string;
    idempotencyKey: string | null;
    result: unknown;
    error: string | null;
    approvalId: string | null;
    decision: unknown;
    finishedAt: Date | null;
  };
  approvals: {
    id: string;
    status: string;
    expiresAt: Date;
    taskId: string;
    resolvedAt: Date | null;
    summary: string;
    toolCallId: string;
    shortCode: string;
    payload: unknown;
    resolutionPayload: unknown;
    requestedAt: Date;
    resolvedVia: string | null;
    notifiedChannels: string[];
    createdPolicyId: string | null;
  };
  applicationConfirmations: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date;
    lastError: string | null;
    conversationId: string | null;
    role: string;
    sourceTaskId: string;
    company: string;
    expectedSenderEmails: string[];
    confirmationTokenHash: string;
    confirmationTokenHint: string;
    trackerUpdate: unknown;
    documentUpdate: unknown;
    actionState: unknown;
    confirmationMessageId: string | null;
    confirmationFrom: string | null;
    confirmedAt: Date | null;
  };
  approvalPolicies: {
    id: string;
    match: unknown;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    version: number;
    enabled: boolean;
    toolName: string;
    templateKey: string;
    effect: string;
    createdVia: string;
  };
  anomalies: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    kind: string;
    toolName: string;
    policyId: string | null;
    observed: number;
    expected: number;
    toolCallIds: string[];
    detail: string;
    windowLabel: string;
    subjectKey: string;
  };
  assistantHealthAlerts: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    kind: string;
    detail: string;
    observationCount: number;
    firstSeenAt: Date;
    lastSeenAt: Date;
    lastNotifiedAt: Date | null;
  };
  skills: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    embedding: number[] | null;
    sourceTaskId: string | null;
    preconditions: string;
    steps: string;
    gotchas: string;
    originTrust: string;
    ownerAuthored: boolean;
    useCount: number;
    successCount: number;
    failureCount: number;
    lastVerifiedAt: Date | null;
    deprecated: boolean;
  };
  improvementProposals: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    kind: string;
    rationale: string;
    change: unknown;
    evidenceIds: string[];
  };
  memories: {
    id: string;
    createdAt: Date;
    agentId: string;
    expiresAt: Date | null;
    embedding: number[] | null;
    sourceTaskId: string | null;
    kind: string;
    confidence: string;
    contentHash: string;
    goalId: string | null;
    originTrust: string;
    category: string;
    content: string;
    importance: number;
    quarantined: boolean;
    subjectContactId: string | null;
    domain: string | null;
    validFrom: Date | null;
    validUntil: Date | null;
    supersededById: string | null;
    ownerConfirmed: boolean;
    pinned: boolean;
    source: string | null;
    lastAccessedAt: Date | null;
    lastConsolidatedAt: Date | null;
  };
  memoryTombstones: { id: string; createdAt: Date; contentHash: string; reason: string };
  ownerCard: { id: number; content: string; compiledAt: Date };
  contacts: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    trust: string;
    aliases: string[];
    emails: string[];
    phones: string[];
    relationship: string;
    notes: string;
  };
  knowledgeGraphEntities: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    kind: string;
    canonicalKey: string;
    label: string;
    preferredLabel: string | null;
    contactId: string | null;
  };
  knowledgeGraphEntityAliases: {
    id: string;
    createdAt: Date;
    agentId: string;
    canonicalKey: string;
    entityId: string;
  };
  knowledgeGraphSources: {
    createdAt: Date;
    updatedAt: Date;
    status: string;
    lastError: string | null;
    contentHash: string;
    subjectContactId: string | null;
    memoryId: string;
    extractionVersion: number;
    nextRetryAt: Date | null;
    attempts: number;
  };
  knowledgeGraphRelations: {
    id: string;
    createdAt: Date;
    agentId: string;
    sourceFingerprint: string;
    confidence: string;
    validFrom: string | null;
    validUntil: string | null;
    subjectEntityId: string;
    predicate: string;
    objectEntityId: string;
    sourceMemoryId: string;
    evidenceQuote: string | null;
    ordinal: number;
    reviewStatus: string;
    reviewedAt: Date | null;
  };
  occasions: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    kind: string;
    originTrust: string;
    quarantined: boolean;
    notes: string;
    ownerConfirmed: boolean;
    source: string | null;
    label: string;
    contactId: string;
    month: number;
    day: number;
    year: number | null;
    recurrence: string;
    leadDays: number;
  };
  importSources: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    taskId: string | null;
    kind: string;
    error: string | null;
    source: string;
    workspacePath: string;
    itemsTotal: number | null;
    itemsProcessed: number;
    memoriesSaved: number;
    memoriesQuarantined: number;
  };
  models: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    enabled: boolean;
    label: string;
    capabilities: unknown;
    promptCostPerMTok: string | null;
    completionCostPerMTok: string | null;
    latencyClass: string;
  };
  modelRoles: {
    updatedAt: Date;
    role: string;
    primaryModel: string;
    fallbackModel: string;
    params: unknown;
  };
  modelCalls: {
    id: string;
    createdAt: Date;
    taskId: string | null;
    role: string;
    model: string;
    inputTokens: number;
    outputTokens: number;
    costUsd: string;
    latencyMs: number | null;
    finishReason: string | null;
    openrouterGenerationId: string | null;
  };
  /** What a model was asked and what it answered. Written only when capture is on. */
  modelCallAudit: {
    id: string;
    createdAt: Date;
    modelCallId: string | null;
    taskId: string | null;
    role: string;
    model: string;
    method: string;
    capture: string;
    systemPrompt: string | null;
    input: string | null;
    output: string | null;
    truncated: boolean;
    finishReason: string | null;
    latencyMs: number | null;
    inputTokens: number;
    outputTokens: number;
  };
  costEvents: {
    id: string;
    createdAt: Date;
    description: string;
    taskId: string | null;
    toolCallId: string | null;
    source: string;
    quantity: string | null;
    unit: string | null;
    unitPriceUsd: string | null;
    usd: string;
    reservationId: string | null;
  };
  costReservations: {
    id: string;
    createdAt: Date;
    status: string;
    description: string;
    taskId: string | null;
    source: string;
    estimatedUsd: string;
    actualUsd: string | null;
    reconciledAt: Date | null;
  };
  rateTable: { updatedAt: Date; unit: string; unitPriceUsd: string; key: string };
  budgets: {
    updatedAt: Date;
    scope: string;
    limitUsd: string;
    softPct: number;
    onSoft: string;
    onHard: string;
  };
  toolCache: { expiresAt: Date; toolName: string; result: unknown; cacheKey: string };
  rateLimits: {
    updatedAt: Date;
    scope: string;
    maxPerHour: number | null;
    maxPerDay: number | null;
  };
  writingSamples: {
    id: string;
    createdAt: Date;
    text: string;
    embedding: number[] | null;
    register: string;
    context: string;
  };
  voiceProfile: {
    id: number;
    signature: string;
    updatedAt: Date;
    description: string;
    dos: unknown;
    donts: unknown;
  };
  gmailSyncState: {
    updatedAt: Date;
    mailbox: string;
    lastHistoryId: bigint | null;
    cursor: unknown;
    watchExpiration: Date | null;
  };
  emailIngest: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    conversationId: string | null;
    channelMessageId: string;
    category: string;
    importance: number;
    reason: string;
    fromEmail: string;
    subject: string;
    contentTrust: string;
    authenticated: boolean;
    actionable: boolean;
    dates: unknown;
    triaged: boolean;
    extractedAt: Date | null;
  };
  suggestions: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date;
    conversationId: string | null;
    origin: string;
    snoozedUntil: Date | null;
    summary: string;
    proposedAction: string;
    sourceRef: string;
    acceptedTaskId: string | null;
  };
  schedules: {
    id: string;
    name: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    enabled: boolean;
    cron: string;
    taskTemplate: unknown;
    lastRunAt: Date | null;
    nextRunAt: Date | null;
  };
  watches: {
    id: string;
    name: string;
    match: unknown;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    status: string;
    expiresAt: Date;
    conversationId: string | null;
    kind: string;
    state: unknown;
    tier: string;
    fireCount: number;
    maxFires: number | null;
    lastFiredAt: Date | null;
    nextPollAt: Date | null;
    pollIntervalSeconds: number | null;
  };
  watchFires: {
    id: string;
    createdAt: Date;
    agentId: string;
    summary: string;
    watchId: string;
    triggerRef: string;
    excerpt: string;
  };
  notificationPrefs: {
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    quietStartMin: number | null;
    quietEndMin: number | null;
    ambientDailyCap: number | null;
  };
  proactivePings: {
    id: string;
    createdAt: Date;
    agentId: string;
    channel: string;
    reason: string | null;
    urgency: string;
    delivered: boolean;
  };
  proactiveMoments: {
    id: string;
    agentId: string;
    kind: string;
    summary: string;
    momentKey: string;
    pinged: boolean;
    deliveredAt: Date;
  };
  calendarEventSnapshots: {
    id: string;
    agentId: string;
    calendarId: string;
    eventId: string;
    iCalUID: string | null;
    summary: string;
    start: string;
    end: string;
    status: string | null;
    attendeeResponseHash: unknown;
    updatedAt: Date;
  };
  canaryRuns: {
    id: string;
    status: string;
    startedAt: Date;
    error: string | null;
    finishedAt: Date | null;
    ok: boolean | null;
    checks: unknown;
    browserCallbackTokenHash: string | null;
    browserResult: unknown;
  };
  files: {
    id: string;
    createdAt: Date;
    agentId: string;
    taskId: string | null;
    workspacePath: string;
    mime: string;
    bytes: number;
    sha256: string | null;
  };
  documents: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    trust: string;
    error: string | null;
    source: string;
    sourceRef: string;
    mime: string;
    sha256: string;
    fileId: string;
    extractor: string;
    chunkCount: number;
    charCount: number;
    processorTokenHash: string | null;
    processorStartedAt: Date | null;
    processorAttempts: number;
    processedTextPath: string | null;
  };
  documentChunks: {
    id: string;
    createdAt: Date;
    agentId: string;
    text: string;
    embedding: number[] | null;
    charCount: number;
    documentId: string;
    chunkIndex: number;
  };
  locationPings: {
    id: string;
    createdAt: Date;
    agentId: string;
    source: string;
    label: string;
    lat: string;
    lng: string;
    accuracyM: number | null;
    timeZone: string | null;
    capturedAt: Date;
  };
  ambientSnapshots: {
    id: string;
    agentId: string;
    block: string;
    flags: unknown;
    sources: unknown;
    computedAt: Date;
  };
  dreamNotes: {
    id: string;
    createdAt: Date;
    agentId: string;
    expiresAt: Date;
    kind: string;
    content: string;
    refIds: string[];
  };
  deviceTokens: {
    id: string;
    createdAt: Date;
    agentId: string;
    lastSeenAt: Date;
    token: string;
    platform: string;
    environment: string;
    invalidatedAt: Date | null;
  };
  selfMaintenance: {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    agentId: string;
    title: string;
    status: string;
    proposalId: string | null;
    diagnosis: string;
    targetArea: string;
    blockedReason: string | null;
    prNumber: number | null;
    prUrl: string | null;
  };
  responseChecks: {
    id: string;
    createdAt: Date;
    taskId: string;
    promptVersion: number;
    plannerVersion: number | null;
    blocked: boolean;
    unsupportedCount: number;
    mustActRetries: number;
    degradedSteps: number;
    outputVerificationAttempted: boolean;
    outputVerificationRevised: boolean;
    outputVerificationUnavailable: boolean;
  };
  recallMetrics: {
    id: string;
    createdAt: Date;
    agentId: string;
    conversationId: string | null;
    taskId: string | null;
    path: string;
    graphAttempted: boolean;
    graphFailed: boolean;
    historyFailed: boolean;
    graphCandidates: number;
    graphUsed: number;
    historyTier: string;
    historyUsed: number;
    sourceCount: number;
  };
  recallFeedback: {
    id: string;
    createdAt: Date;
    agentId: string;
    messageId: string;
    sourceCount: number;
    verdict: string;
  };
}
export type RecordOf<K extends keyof Records> = Records[K];
